---

- name: Fail if required settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - "matrix_mautrix_wsproxy_users"
    - "matrix_mautrix_wsproxy_sync_proxy_shared_key"
